DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CLIENTS;
DROP TABLE IF EXISTS COMPANIES;
DROP TABLE IF EXISTS AGENTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
	  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	  LOGIN VARCHAR(50) NOT NULL,
      PASSWORD VARCHAR(255) NOT NULL,
      PERMISSION_LEVEL INT
);

CREATE TABLE AGENTS
(
	  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	  NAME VARCHAR(50) NOT NULL
);

CREATE TABLE COMPANIES
(
	  ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	  NAME VARCHAR(50) NOT NULL,
	  CHARGE_PERCENT DOUBLE NOT NULL
);

CREATE TABLE CLIENTS
(
	ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID INT(11) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    NAME VARCHAR(255),
    CNPJ VARCHAR(18),
    STATE_REGISTRATION VARCHAR(9),
    ADDRESS VARCHAR(255),
    DISTRICT VARCHAR(100),
    ZIPCODE VARCHAR(9),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    PHONE VARCHAR(15),
    MOBILE VARCHAR(15),
    CONTACT VARCHAR(100),
    EMAIL VARCHAR(100),
    DISCOUNT_PERCENT DOUBLE,
    VISIT_INTERVAL INT,
    CONSTRAINT FK_CLIENT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE ORDERS
(
	ID BIGINT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	COMPANY_ID INT(11) NOT NULL,
	CLIENT_ID INT(11) NOT NULL,
    AGENT_ID INT(11) NOT NULL,
    USER_ID INT(11) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
	ORDER_AMOUNT DOUBLE NOT NULL,
	ORDER_INVOICED  DOUBLE NOT NULL,
	DISCOUNT  DOUBLE,
	OBSERVATION VARCHAR(255),	
	ORDER_DATE DATE,
	INVOICE_DATE DATE,
	BONUS_AMOUNT DOUBLE,
	BONUS_INVOICED DOUBLE,
	CANCELLED BOOLEAN NOT NULL,
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID),
    CONSTRAINT FK_ORDER_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (ID),
	CONSTRAINT FK_ORDER_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENTS (ID),
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);